Jenkinsfile_nightly

Jenkins Nightly update

---

Jenkinsfile_CNP

https://tools.hmcts.net/jira/browse/DTSPO-7153
sync demo branch with master branch
```
[ ] Yes
[x] No
```

sync demo env with master branch for ds-ui

---

Jenkinsfile_CNP

Preview test configuration

---

Jenkinsfile_CNP
src/test/config.js

smoketest fix for AAT env

---

package.json
src/main/steps/common/components/full-name.ts
src/main/steps/common/form/form.njk
src/main/steps/edge-case/full-name/content.test.ts
src/main/steps/edge-case/full-name/content.ts
src/main/steps/edge-case/full-name/template.njk
src/main/steps/edge-case/private-law-application-type/content.test.ts
src/main/steps/edge-case/private-law-application-type/content.ts
src/main/steps/errorMesages.ts

merge with master branch

---

package.json

test fixes

---

Jenkinsfile_CNP
Jenkinsfile_nightly
README.md
charts/ds-ui/Chart.yaml
charts/ds-ui/values.yaml
docker-compose.yml
infrastructure/main.tf
infrastructure/variables.tf
sonar-project.properties
src/test/e2e/config.js

Changes to rename namespace and infra configs

---

codecept.conf.js
src/test/e2e/pages/ApplytoApplicant.page.js
src/test/e2e/pages/Family.page.js
src/test/e2e/pages/LandingPage.js
src/test/e2e/tests/SubmitApplication_test.js

isdb-60 and 61

---

codecept.conf.js
src/test/e2e/pages/Adoption.page.js
src/test/e2e/tests/SubmitApplication_test.js

isdb-62 changes

---

src/main/app/case/CaseApi.ts
src/main/app/case/case.ts
src/main/app/controller/GetController.ts
src/main/app/controller/PostController.ts
src/main/modules/oidc/index.ts
src/main/steps/edge-case/full-name/content.ts

title bar fix

---

src/main/modules/oidc/index.ts

fix merge conflict issue

---

src/main/app/form/validation.test.ts
src/main/app/form/validation.ts
src/main/steps/edge-case/date-of-birth/content.test.ts
src/main/steps/edge-case/date-of-birth/content.ts
src/main/steps/edge-case/date-of-birth/template.njk

feat: date of birth changes(ISDB-64)

---

src/main/app/address/AddressLookupPostControllerBase.ts
src/main/app/address/SelectAddressPostControllerBase.ts
src/main/app/controller/PostController.ts
src/main/steps/edge-case/contact-details/content.ts

fix title bar issue - back button

---

config/default.yaml
src/main/app/fee/fee-lookup-api.test.ts
src/main/app/fee/fee-lookup-api.ts
src/main/assets/js/go-back.ts
src/main/steps/constants.ts
src/main/steps/edge-case/edgecaseSequence.test.ts
src/main/steps/edge-case/edgecaseSequence.ts
src/main/steps/edge-case/payment/pay-your-fee/content.test.ts
src/main/steps/edge-case/payment/pay-your-fee/content.ts
src/main/steps/edge-case/payment/pay-your-fee/get.test.ts
src/main/steps/edge-case/payment/pay-your-fee/get.ts
src/main/steps/edge-case/payment/pay-your-fee/template.njk
src/main/steps/urls.ts
src/test/unit/utils/mockFeeLookupResponses.ts

feat: fee screen and api integration(ISDB-121)

---

codecept.conf.js
src/test/e2e/pages/UploadDocuments.page.js
src/test/e2e/tests/SubmitApplication_test.js

upload document changes

---

config/default.yaml
config/development.yaml
src/main/steps/edge-case/upload-your-documents/template.njk
src/main/steps/edge-case/upload-your-documents/uploadDocPostController.ts

added file handler comments

---

codecept.conf.js
src/test/e2e/tests/SubmitApplication_test.js

screen chages of 121

---

src/main/steps/edge-case/edgecaseSequence.ts
src/main/steps/edge-case/upload-your-documents/content.ts
src/main/steps/edge-case/upload-your-documents/uploadDocPostController.ts

Sequence added for upload documents

---

src/main/steps/edge-case/full-name/content.ts

to check deployment issue. dummy change, need to revert.

---

.gitignore
codecept.conf.js
src/main/app/case/case.ts
src/main/app/case/definition.ts
src/main/modules/oidc/index.ts
src/main/steps/edge-case/edgecaseSequence.ts
src/main/steps/edge-case/user-role/UserRolePostController.test.ts
src/main/steps/edge-case/user-role/content.test.ts
src/main/steps/edge-case/user-role/content.ts
src/main/steps/edge-case/user-role/userRolePostController.ts
src/main/steps/errorMesages.ts
src/main/steps/urls.ts
src/test/e2e/pages/DetermineApplicantRole.page.js
src/test/e2e/tests/SubmitApplication_test.js
test-results/result.xml
yarn.lock

feat: implement user-role screen(ISDB-214)

---

Jenkinsfile_CNP
charts/fis-ds-web/Chart.yaml
charts/fis-ds-web/values.aat.template.yaml
charts/fis-ds-web/values.preview.template.yaml

Fix idam issue for pr

---

config/default.yaml
config/development.yaml
src/main/app/case/CaseApi.ts
src/main/app/case/answers/formatDate.ts
src/main/app/case/case.ts
src/main/app/case/definition.ts
src/main/app/controller/GetController.ts
src/main/modules/health/index.ts
src/main/modules/oidc/index.ts
src/main/resources/user-role/translation.json
src/main/steps/common/constants/apiConstants.ts
src/main/steps/common/constants/commonConstants.ts
src/main/steps/edge-case/check-your-answers/utils.ts
src/main/steps/edge-case/upload-additional-documents/uploadDocPostController.test.ts
src/main/steps/edge-case/upload-additional-documents/uploadDocPostController.ts
src/main/steps/edge-case/upload-your-documents/uploadDocPostController.test.ts
src/main/steps/edge-case/upload-your-documents/uploadDocPostController.ts
src/main/steps/edge-case/user-role/UserRolePostController.test.ts
src/main/steps/edge-case/user-role/content.test.ts
src/main/steps/edge-case/user-role/content.ts
src/main/steps/edge-case/user-role/template.njk
src/main/steps/edge-case/user-role/userRolePostController.ts
src/test/e2e/pages/DetermineApplicantRole.page.js

https://tools.hmcts.net/jira/browse/ISDB-259
- created new common and ap constant files
- updated fis cos url in config.
- removed payment and document management url from config
```
[ ] Yes
[x] No
```

ISDB 259 - first name, last name and email changes

---

Jenkinsfile_CNP
Jenkinsfile_nightly
bin/run-crossbrowser-tests.sh

disabled full funtional from nightly and added cross browser script

---

config/default.yaml
config/development.yaml
saucelabs.conf.js
src/main/resources/upload-your-documents/translation.json
src/main/steps/edge-case/upload-your-documents/uploadDocPostController.test.ts
src/main/steps/edge-case/upload-your-documents/uploadDocPostController.ts
src/test/e2e/pages/AdditionalDocuments.page.js
src/test/e2e/pages/UploadDocuments.page.js
src/test/e2e/tests/smoke_test.js

https://tools.hmcts.net/jira/browse/ISDB-287
- user will get error when continue without uploading a file
- user will get error after clicking of upload button, in case no file is selected.
- remove document management url.
- To call fis cos api, only one base url will be used.
```
[ ] Yes
[x] No
```

ISDB-287 - Upload document screen changes

---

src/main/app/case/CaseApi.ts
src/main/app/case/definition.ts
src/main/app/controller/PostController.test.ts
src/main/app/controller/PostController.ts

fix eventName passing from UI

---

README.md
charts/fis-ds-web/Chart.yaml
charts/fis-ds-web/values.yaml
config/default.yaml
config/development.yaml

Change readme file

---

charts/fis-ds-web/values.aat.template.yaml

- https://tools.hmcts.net/jira/browse/DTSPO-12138
NA
Added entry as suggested by platops to fix master build.
- https://tools.hmcts.net/jira/browse/DTSPO-12138
```
[ ] Yes
[ ] No
```

Added entry as suggested by platops to fix master build.

---

src/main/app/auth/service/get-service-auth-token.ts

ithc deployment

---

charts/fis-ds-web/Chart.yaml
charts/fis-ds-web/values.yaml
infrastructure/main.tf
infrastructure/output.tf
infrastructure/variables.tf
src/main/modules/properties-volume/index.ts

https://tools.hmcts.net/jira/browse/PRL-6115
Redis setup for DSS Create case

Redis setup for DSS create case component

---

src/test/e2e/codecept.conf.js

fix cdecept

---

charts/fis-ds-web/Chart.yaml
charts/fis-ds-web/values.aat.template.yaml
charts/fis-ds-web/values.preview.template.yaml
charts/fis-ds-web/values.yaml
src/main/modules/nunjucks/index.ts
src/main/server.ts

Updated values files

---

config/custom-environment-variables.yaml
src/main/app/case/CaseApi.ts

Cos url config

---

package.json
src/main/assets/js/cookie.ts
src/main/assets/js/data-layer.ts
src/main/assets/js/index.ts
src/main/steps/common/common.content.ts
src/main/steps/cookie-banner/template.njk
src/main/steps/edge-case/cookies/template.njk
yarn.lock

https://tools.hmcts.net/jira/browse/PRL-6848
Fixes cookie integration

PRL-6848: Fix cookie integration

---

src/main/app/case/CaseApi.ts
src/main/app/case/api-utility.ts
src/main/app/case/case.ts
src/main/app/case/definition.ts
src/main/app/case/to-api-format.ts
src/main/app/controller/GetController.ts
src/main/app/controller/PostController.ts
src/main/app/form/Form.ts
src/main/modules/oidc/index.ts
src/main/resources/pay-your-fee/translation.json
src/main/routes.ts
src/main/steps/edge-case/application-submitted/template.njk
src/main/steps/edge-case/check-your-answers/utils.ts
src/main/steps/edge-case/contact-details/content.ts
src/main/steps/edge-case/contact-details/postController.ts
src/main/steps/edge-case/edgecaseSequence.ts
src/main/steps/edge-case/help-with-fee/content.ts
src/main/steps/edge-case/pay-your-fee/PayAndSubmitPostController.ts
src/main/steps/edge-case/pay-your-fee/content.ts
src/main/steps/edge-case/pay-your-fee/routeGuard.ts
src/main/steps/edge-case/pay-your-fee/template.njk
src/main/steps/edge-case/payments/paymentController.ts
src/main/steps/edge-case/select-court/content.ts
src/main/steps/edge-case/select-court/routeGuard.ts
src/main/steps/edge-case/type-of-application/content.test.ts
src/main/steps/edge-case/type-of-application/content.ts
src/main/steps/edge-case/type-of-application/routeGuard.ts
src/main/steps/home/get.ts
src/main/steps/urls.ts

https://tools.hmcts.net/jira/browse/PRL-6585

feat(PRL-6585): Refactor case create & update

---

src/main/resources/user-role/translation.json
src/main/steps/edge-case/user-role/content.ts

https://tools.hmcts.net/jira/browse/PRL-6100

feat(PRL-6100): Ammends to user type screen

---

src/main/app/case/api-utility.ts
src/main/resources/select-court/translation.json
src/main/resources/upload-your-documents/translation.json
src/main/steps/edge-case/select-court/content.ts
src/main/steps/edge-case/select-court/template.njk
src/main/steps/edge-case/type-of-application/routeGuard.ts
src/main/steps/edge-case/upload/upload-your-documents/content.ts
src/main/steps/edge-case/upload/upload-your-documents/template.njk

See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)

feat(6104): Amends to upload doc screen

---

src/main/app/case/api-utility.ts
src/main/app/case/case.ts
src/main/app/case/definition.ts
src/main/resources/check-your-answers/translation.json
src/main/resources/user-role/translation.json
src/main/steps/edge-case/check-your-answers/content.ts
src/main/steps/edge-case/check-your-answers/form.njk
src/main/steps/edge-case/check-your-answers/utils.test.ts
src/main/steps/edge-case/check-your-answers/utils.ts
src/main/steps/edge-case/select-court/content.ts
src/main/steps/edge-case/user-role/content.ts
src/main/steps/edge-case/user-role/userRolePostController.ts

See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)

feat(PRL-6919): Revalidate CYA and added welsh infra

---

src/main/steps/edge-case/payments/paymentHelper.test.ts

improved paymentHelper test file coverage from 93.3% to 100%

Updated paymentHelper test file

---

src/main/app/case/CaseApi.test.ts

Improved test coverage of CaseAPI from 71.1% to 94.5%

Improving test coverage for Case API
